sudo: required
services: 
        - docker

before_install: 
    - docker build -t xenonpluton/react-test-f ./client/Dockerfile.dev ./client
    
script: 
    - docker run xenonpluton/react-test npm test -- --coverage

after_sucess:
    - docker build -t xenonpluton/multi-client ./client
    - docker build -t xenonpluton/multi-nginx ./nginx
    - docker build -t xenonpluton/multi-server ./server
    - docker build -t xenonpluton/multi-worker ./worker
    #log in docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push xenonpluton/multi-client
    - docker push xenonpluton/multi-nginx
    - docker push xenonpluton/multi-server
    - docker push xenonpluton/multi-worker

